server2: nnnnn

mail:
  host: smtp.163.com
  user: liujiao18880441791@163.com
  pwd: YLCXBMBGITCYBFTN
  from: liujiao18880441791@163.com

iplimit:
  time: 30000
  count: 3


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.12.173:3306/mapboxx?characterEncoding=utf8
    username: lxq
    password: Lxq410221@5214
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
